/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SavedDestination = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'longitude' : IDL.Float64,
  'notes' : IDL.Text,
});
export const SavedStop = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'destinationId' : IDL.Nat,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  'deleteDestination' : IDL.Func([IDL.Nat], [], []),
  'deleteStop' : IDL.Func([IDL.Nat], [], []),
  'getAllDestinations' : IDL.Func([], [IDL.Vec(SavedDestination)], ['query']),
  'getStopsForDestination' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SavedStop)],
      ['query'],
    ),
  'saveDestination' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'saveStop' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'updateDestinationNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SavedDestination = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'longitude' : IDL.Float64,
    'notes' : IDL.Text,
  });
  const SavedStop = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'destinationId' : IDL.Nat,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    'deleteDestination' : IDL.Func([IDL.Nat], [], []),
    'deleteStop' : IDL.Func([IDL.Nat], [], []),
    'getAllDestinations' : IDL.Func([], [IDL.Vec(SavedDestination)], ['query']),
    'getStopsForDestination' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SavedStop)],
        ['query'],
      ),
    'saveDestination' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'saveStop' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'updateDestinationNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };